### ISSUE TITLE
VectorGridProtobuf() instead of VectorTileLayer()

### ISSUE THREAD

**Issue by BasAndriessen** [ellipsis-drive/folium#1]
Hi Daniel,

When I use vc = VectorGridProtobuf(url,layerName,options) instead of vc = VectorTileLayer(url, "layer", options) to add a vector layer to a 
Leafmap map with Folium backend, followed by conversion to streamlit-folium map, the height is not altered by adding the vector layer. Use the following import statement: from folium.plugins import VectorGridProtobuf.

In Dash I did not have this problem. 

Cheers,

Bas

**Comment by danielvandermaas** [comment]
We updated the package to use folium-vectorgrid instead

**Comment by danielvandermaas** [comment]
Issue has been resolved in 0.0.5
